### ISSUE TITLE
Problem with reversal receipt on Datecs WP-50X

### ISSUE THREAD

**Issue by StoyanMalchev** [erpnet/ErpNet.FP#82]
Response is "ok":true 
but not any printing.
No problems with same request on TREMOL S21
[debug.log](https://github.com/erpnet/ErpNet.FP/files/3481199/debug.log)

**Comment by g-vvv** [comment]
No description. Please provide description, debug.log. Follow the rules for bug report.

**Comment by g-vvv** [comment]
The version, you use is not supported. Is too old. Please update to latest release from here, and try again:
https://github.com/erpnet/ErpNet.FP/releases/latest/download/ErpNet.FP.Setup.msi

**Comment by StoyanMalchev** [comment]
Another problem with current release.
Cant print receipt.
[data.txt](https://github.com/erpnet/ErpNet.FP/files/3508137/data.txt)
[Responce.txt](https://github.com/erpnet/ErpNet.FP/files/3508139/Responce.txt)

No such problem with previous version.

**Comment by i-argentinski** [comment]
Hi,

You had to be using really ancient version before :)

1. You *must* have at least one item of type "sale". Otherwise, there is nothing to fiscalize and an error is returned.

2. It is preferrable that you no longer use "isComment"=true, because it is outdated and can be removed in future versions. The new syntax allows extensibility and will be the only syntax supported in the future.

Use "type"="sale" or "type"="comment"
(See docs for more info and examples)

**Comment by i-argentinski** [comment]
3. You have to provide taxGroup (perhaps taxGroup=2) when fiscalizing an amount.

**Comment by g-vvv** [comment]
Please always provide debug.log. Otherwise we cannot help you.
